# Checks for any broken links in markdown files
name: Check Markdown links

on: workflow_call

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: tcort/github-action-markdown-link-check@e047c5b37f24ab722bbef1a27b6fab7f96bc4068 # v1
      with:
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/markdown-link-check.config.json'

